{
  parserClass="by.home.acs.language.parser.ACSScriptParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ACSScript"
  psiImplClassSuffix="Impl"
  psiPackage="by.home.acs.language.psi"
  psiImplPackage="by.home.acs.language.psi.impl"

  elementTypeHolderClass="by.home.acs.language.ACSScriptTypes"
  elementTypeClass="by.home.acs.language.psi.ACSScriptElementType"
  tokenTypeClass="by.home.acs.language.psi.ACSScriptTokenType"

  psiImplUtilClass="by.home.acs.language.psi.impl.ACSScriptPsiImplUtil"
}

{
    tokens = [
        IDENTIFIER = 'regexp:[a-zA-Z_][a-zA-Z0-9_]*'
        WHITE_SPACE = 'regexp:\s+'
        NUMBER = '-?[0-9]+'
        STRING = 'regexp:^"(.*?)"'
        CHARACTER
        FLOAT = 'regexp:^[+-]?\d+(\.\d+)?$'
    ]
}

ACSScriptFile ::= (COMMENT|Definition*)

Definition ::= (FunctionDefinition | ScriptDefinition | DirectivesDeclaration | GlobalModifier | VariableDefinition)

FunctionDefinition ::= function (VoidType | Type) IDENTIFIER '(' ')'  '{' FunctionBody '}'

ScriptDefinition ::= SCRIPT ( STRING | NUMBER) (ScriptType)? ('(' Type IDENTIFIER')' | '(' VoidType ')')?  (NetType)? '{' ScriptBody '}'

ScriptType ::= OPEN | ENTER | RETURN | RESPAWN | DEATH | LIGHTNING | UNLOADING | DISCONNECT | KILL | REOPEN

DirectivesDeclaration ::= IncludeDeclaration | ImportDeclaration | DefineDeclaration | LibraryDeclaration

IncludeDeclaration ::= '#' include STRING

ImportDeclaration ::= '#' import STRING

DefineDeclaration ::= '#' define IDENTIFIER IDENTIFIER  //TODO need to add operator support here with numbers

LibraryDeclaration ::= '#' library STRING

GlobalModifier ::= (global | world) Type IDENTIFIER':'IDENTIFIER';'

StaticModifier ::= static

NetType ::= net

VoidType ::= void

FunctionBody ::= Statement*

Statement ::= VariableDefinition | AssignmentStatement | FunctionInvocation | ConditionalOperator | Loops | ReturnOperator

ScriptBody ::= ScriptStatement*

ScriptStatement ::= VariableDefinition | VariableInitialization | AssignmentStatement | FunctionInvocation | ConditionalOperator | Loops

CaseOperator ::=   case (IDENTIFIER | NUMBER | STRING) ':'  (FunctionInvocation | VariableDefinition)? (SwitchStatement)?  (break ';')? CaseOperator? (default ':' FunctionInvocation)?

AssignmentStatement ::= IDENTIFIER '=' (FunctionInvocation)

VariableDefinition ::= StaticModifier? (ArrayType | Type) IDENTIFIER (';' | ('=' (FunctionInvocation | VariableInitialization | Operator)))

VariableInitialization ::= ( STRING | CHARACTER | EmptyString | LogicalType | ArrayInitializer | NUMBER | FLOAT) ';'

Operator ::=  IDENTIFIER ('=' | '+' | '-' | '*' | '/' | '%' | '&' | '|' | '^' | '~' | '<<' | '>>' | '==' | '!=' | '>' | '<' | '>=' | '<=' | '&&' | '||' | '!' | '+=' | '++' | '-=' | '--' | '*=' | '/=' | '%=' | '&=' | '|=' | '^=' | '<<=' | '>>=') IDENTIFIER? NUMBER? STRING?';' // never used yet

Loops ::= forLoop | whileLoop | untilLoop | doWhileLoop | doUntilLoop

forLoop ::= for '(' IDENTIFIER ';' LogicalType ';' IDENTIFIER ')' '{' Statement '}' // not finished yet cuz need to fix operators

whileLoop ::= while '(' LogicalType ')' '{' Statement? '}'

untilLoop ::= until '(' LogicalType ')' '{' Statement? '}'

doWhileLoop ::= do '{' Statement? '}' while '(' LogicalType ')' ';'

doUntilLoop ::= do '{' Statement? '}' until '(' LogicalType ')' ';'

Type ::= (IntType | StringType | BoolType)

BoolType ::= bool

IntType ::= int

StringType ::= str

EmptyString ::= '""'

ArrayType ::= (Type) '[' ']'

ArrayInitializer ::= '{' ArrayInitializers? '}'

ArrayInitializers ::= (NUMBER | STRING) (',' ArrayInitializers)?

LogicalType ::= true | false

ReturnOperator ::= return ';' | return IDENTIFIER ';' // Use something else but IDENTIFIER later

FunctionInvocation ::= IDENTIFIER '(' ')' ';' ReturnOperator?

ConditionalOperator ::= IfThenStatement | IfThenElseStatement |  SwitchStatement

IfThenStatement ::= if '(' LogicalType ')' Statement

IfThenElseStatement ::= if '(' LogicalType ')' '{' FunctionBody '}' (else ('{' FunctionBody '}' | IfThenElseStatement) )?

SwitchStatement ::= switch '(' (IDENTIFIER | NUMBER) ')' '{' CaseOperator '}'



