{
  parserClass="by.home.acs.language.parser.ACSScriptParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ACSScript"
  psiImplClassSuffix="Impl"
  psiPackage="by.home.acs.language.psi"
  psiImplPackage="by.home.acs.language.psi.impl"

  elementTypeHolderClass="by.home.acs.language.ACSScriptTypes"
  elementTypeClass="by.home.acs.language.psi.ACSScriptElementType"
  tokenTypeClass="by.home.acs.language.psi.ACSScriptTokenType"

  psiImplUtilClass="by.home.acs.language.psi.impl.ACSScriptPsiImplUtil"
}

{
    tokens = [
        IDENTIFIER = 'regexp:[a-zA-Z_][a-zA-Z0-9_]*'
        WHITE_SPACE = 'regexp:\s+'
        NUMBER = 'regexp:[1-9][0-9]*'
        STRING = 'regexp:^"(.*?)"'
    ]
}


ACSScriptFile ::= (COMMENT|Definition*)

Definition ::= (FunctionDefinition|ScriptDefinition)

FunctionDefinition ::= function IDENTIFIER '(' ')' (returns Type)? '{' FunctionBody '}'

ScriptDefinition ::= SCRIPT (NUMBER | STRING) (ScriptType)? ('(' Type IDENTIFIER')' | '(' VoidType ')')?  (NetType)? '{' FunctionBody '}'

ScriptType ::= OPEN | ENTER | RETURN | RESPAWN | DEATH | LIGHTNING | UNLOADING | DISCONNECT | KILL | REOPEN

NetType ::= net

VoidType ::= void

FunctionBody ::= Statement*

Statement ::= VariableDefinition | AssignmentStatement | FunctionInvocation | ConditionalOperator | ReturnOperator

CaseOperator ::=   case IDENTIFIER ':'  (FunctionInvocation | VariableDefinition)?  (break ';')? CaseOperator? (default ':' FunctionInvocation)?

VariableDefinition ::= Type IDENTIFIER (';' | ('=' ((FunctionInvocation) | VariableInitialization ))?)

VariableInitialization ::= (NUMBER | STRING | LogicalType) ';' // Classify initialization directly

Type ::= int | str | bool

LogicalType ::= true | false

ReturnOperator ::= return ';' | return IDENTIFIER ';' // Use something else but IDENTIFIER later

AssignmentStatement ::= IDENTIFIER '=' FunctionInvocation

FunctionInvocation ::= IDENTIFIER '(' ')' ';' ReturnOperator?

ConditionalOperator ::= IfElseStatement | SwitchStatement

IfElseStatement ::= if '(' LogicalType ')' '{' FunctionBody '}' (else ('{' FunctionBody '}' | IfElseStatement) )?

SwitchStatement ::= switch '(' IDENTIFIER ')' '{' CaseOperator '}'

